apiVersion: v1
kind: Service
metadata:
  name: {{ include "sudo0x-kafka.fullname" . }}
  labels:
    {{- include "sudo0x-kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - name: kafka
      port: {{ .Values.service.port }}
      targetPort: kafka
      protocol: TCP
  selector:
    {{- include "sudo0x-kafka.selectorLabels" . | nindent 4 }}
