apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sudo0x-redis.fullname" . }}-config
  labels:
    {{- include "sudo0x-redis.labels" . | nindent 4 }}
data:
  redis.conf: |
    appendonly {{ .Values.redis.appendonly }}
    maxmemory-policy {{ .Values.redis.maxmemoryPolicy }}
    loglevel {{ .Values.redis.loglevel }}
