{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sudo0x-redis.secretName" . }}
  labels:
    {{- include "sudo0x-redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ required "auth.password is required when existingSecret is not configured" .Values.auth.password | quote }}
{{- end }}
