{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sudo0x-rabbitmq.secretName" . }}
  labels:
    {{- include "sudo0x-rabbitmq.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.usernameKey }}: {{ required "auth.username is required when existingSecret is not configured" .Values.auth.username | quote }}
  {{ .Values.auth.passwordKey }}: {{ required "auth.password is required when existingSecret is not configured" .Values.auth.password | quote }}
{{- end }}
