apiVersion: v1
kind: Service
metadata:
  name: {{ include "sudo0x-rabbitmq.fullname" . }}
  labels:
    {{- include "sudo0x-rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: amqp
      protocol: TCP
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
      protocol: TCP
  selector:
    {{- include "sudo0x-rabbitmq.selectorLabels" . | nindent 4 }}
